In [3]:
from numpy import *

In [2]:
v1 = arange(0, 5)
v1 * 2

array([0, 2, 4, 6, 8])

In [3]:
v1 + 2

array([2, 3, 4, 5, 6])

In [11]:
A = array([[j + i * 10 for j in range(5)] for i in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [5]:
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]), array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

In [6]:
A * A

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [7]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [8]:
A.shape, v1.shape

((5L, 5L), (5L,))

In [9]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

In [10]:
dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [11]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [12]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [13]:
dot(v1, A)

array([300, 310, 320, 330, 340])

In [14]:
dot(v1, v1)

30

In [15]:
M = matrix(A)
v = matrix(v1).T
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [16]:
M

matrix([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])

In [17]:
M*M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [18]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [19]:
v


matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [20]:
v.T * v


matrix([[30]])

In [21]:
v.T

matrix([[0, 1, 2, 3, 4]])

In [22]:
v + M * v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

In [23]:
v = matrix([1, 2, 3, 4, 5 ,6]).T
shape(M), shape(v)

((5L, 5L), (6L, 1L))

In [24]:
M * v

ValueError: shapes (5,5) and (6,1) not aligned: 5 (dim 1) != 6 (dim 0)

In [25]:
C = matrix([[1j, 2j], [3j, 4j]])
C

matrix([[ 0.+1.j,  0.+2.j],
        [ 0.+3.j,  0.+4.j]])

In [26]:
conjugate(C)

matrix([[ 0.-1.j,  0.-2.j],
        [ 0.-3.j,  0.-4.j]])

In [27]:
C.H

matrix([[ 0.-1.j,  0.-3.j],
        [ 0.-2.j,  0.-4.j]])

In [28]:
C

matrix([[ 0.+1.j,  0.+2.j],
        [ 0.+3.j,  0.+4.j]])

In [29]:
real(C)

matrix([[ 0.,  0.],
        [ 0.,  0.]])

In [30]:
imag(C)

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [31]:
angle(C + 1)

array([[ 0.78539816,  1.10714872],
       [ 1.24904577,  1.32581766]])

In [32]:
abs(C)

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [20]:
from scipy.linalg import *

In [34]:
inv(C)

array([[-0.+2.j ,  0.-1.j ],
       [ 0.-1.5j,  0.+0.5j]])

In [35]:
C.I * C

matrix([[  1.00000000e+00+0.j,   0.00000000e+00+0.j],
        [  1.11022302e-16+0.j,   1.00000000e+00+0.j]])

In [36]:
linalg.det(C)

(2.0000000000000004+0j)

In [37]:
linalg.det(C.I)

(0.49999999999999967+0j)

In [14]:
import matplotlib.pyplot as plt
data = genfromtxt('stockholm_td_adj.dat')
shape(data)

(77431L, 7L)

In [40]:
mean(data[:,3])

6.1971096847515854

In [41]:
std(data[:,3]), var(data[:,3])

(8.2822716213405734, 68.596023209663414)

In [42]:
data[:,3].min()

-25.800000000000001

In [43]:
data[:,3].max()


28.300000000000001

In [5]:
d = arange(0, 10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
sum(d)

45

In [7]:
prod(d + 1)

3628800

In [8]:
cumsum(d)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [9]:
cumprod(d + 1)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [12]:
trace(A)

110

In [15]:
unique(data[:1])

array([ -6.10000000e+00,   1.00000000e+00,   1.80000000e+03])

In [16]:
m = rand(3, 3)

NameError: name 'rand' is not defined

In [18]:
from numpy import *

In [22]:
m = rand(3, 3)

NameError: name 'rand' is not defined

In [25]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [27]:
n, m = A.shape

In [28]:
B = A.reshape((1, n * m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [29]:
B[0, 0 : 5] = 5

In [30]:
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [31]:
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [32]:
B = A.flatten()

In [33]:
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [35]:
B[0:5] = 10
B

array([10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [36]:
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [37]:
v = array([1, 2, 3])
shape(v)

(3L,)

In [38]:
v[: newaxis]

array([1, 2, 3])

In [39]:
v

array([1, 2, 3])

In [40]:
shape(v)

(3L,)

In [41]:
v[:, newaxis]

array([[1],
       [2],
       [3]])

In [42]:
v[:, newaxis].shape

(3L, 1L)

In [43]:
v[newaxis,:].shape

(1L, 3L)

In [45]:
a=  array([[1, 2], [3, 4]])

In [46]:
a

array([[1, 2],
       [3, 4]])

In [47]:
repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [48]:
a

array([[1, 2],
       [3, 4]])

In [50]:
tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [51]:
b = array([[5, 6]])

In [52]:
b

array([[5, 6]])

In [53]:
b.shape

(1L, 2L)

In [54]:
concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
concatenate((a, b.T), axis=  1)

array([[1, 2, 5],
       [3, 4, 6]])

In [56]:
vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [59]:
A = array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [60]:
B = A

In [61]:
b[0, 0] = 10

In [62]:
B[0, 0] = 10

In [63]:
B

array([[10,  2],
       [ 3,  4]])

In [64]:
A

array([[10,  2],
       [ 3,  4]])

In [65]:
B = copy(A)

In [66]:
b[0, 0] = -5

In [67]:
B[0, 0] = -5

In [68]:
B

array([[-5,  2],
       [ 3,  4]])

In [69]:
A

array([[10,  2],
       [ 3,  4]])

In [70]:
v = array([1, 2, 3, 4])

In [71]:
v

array([1, 2, 3, 4])

In [72]:
for element in v:
    print element

1
2
3
4


In [73]:
M = array([[1,2], [3, 4]])
for row in M:
    print("row", row)
    for element in row:
        print(element)

('row', array([1, 2]))
1
2
('row', array([3, 4]))
3
4


In [74]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
        M[row_idx, col_idx] = element ** 2

('row_idx', 0, 'row', array([1, 2]))
('col_idx', 0, 'element', 1)
('col_idx', 1, 'element', 2)
('row_idx', 1, 'row', array([3, 4]))
('col_idx', 0, 'element', 3)
('col_idx', 1, 'element', 4)


In [75]:
M

array([[ 1,  4],
       [ 9, 16]])

In [76]:
def Theta(x):
    if x >= 0:
        return 1
    else:
        return 0
    
Theta(array([-3, -3, -3, 0, 1, 2, 3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [77]:
Theta_vec = vectorize(Theta)

In [78]:
Theta_vec(array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

In [79]:
M

array([[ 1,  4],
       [ 9, 16]])

In [80]:
if(M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

at least one element in M is larger than 5


In [81]:
M.dtype

dtype('int32')

In [82]:
M2 = M.astype(float)

In [83]:
M2

array([[  1.,   4.],
       [  9.,  16.]])

In [84]:
M2.dtype

dtype('float64')

In [85]:
M2 = M.astype(bool)

In [86]:
M2

array([[ True,  True],
       [ True,  True]], dtype=bool)