In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
iris.data.shape

(150L, 4L)

In [3]:
iris.target.shape

(150L,)

In [4]:
import numpy as np
np.unique(iris.target)

array([0, 1, 2])

In [5]:
digits = datasets.load_digits()

In [6]:
print(digits.data)

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]


In [7]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [8]:
from sklearn import svm
clf = svm.SVC(gamma = 0.001, C = 100.)
clf.fig(digits.data[:-1], digits.target[:-1])
SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0, degree=3,
  gamma=0.001, kernel='rbf', max_iter=-1, probability=False,
  random_state=None, shrinking=True, tol=0.001, verbose=False)

AttributeError: 'SVC' object has no attribute 'fig'

In [9]:
from sklearn import linear_model
clf = linear_model.LinearRegression()
clf.fit ([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
clf.coef_


array([ 0.5,  0.5])

In [10]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier()
knn.fit(iris.data, iris.target) 
knn.predict([[0.1, 0.2, 0.3, 0.4]])

array([0])

In [15]:
from scipy import misc
lena = misc.face().astype(np.float32)
X = lena.reshape((-1, 1)) # We need an (n_sample, n_feature) array
k_means = cluster.KMeans(n_clusters=5)
k_means.fit(X) 
values = k_means.cluster_centers_.squeeze()
labels = k_means.labels_
lena_compressed = np.choose(labels, values)
lena_compressed.shape = lena.shape

NameError: name 'cluster' is not defined